### ISSUE TITLE
Games played/won are not saved to the database

### ISSUE THREAD

**Issue by lakner** [albert2804/transendence#83]
statistics need to be saved in the database. 

I just added a couple of fields to the CustomUser class, but these need to be incremented at the end of every game.

**Comment by lakner** [comment]
I just noticed that there already is a model for user statistics in `backend/models/users.py`. That seems overly complicated, can we just save them along with the rest of the user data?

**Comment by Tilmanfs95** [comment]
I don't know about the backend/models/users.py model.
But we have an own model for ranked games ("RemoteGame"-model in the remote_game app.)
I think the best way is to query this models entries to get the game statistics of a user.

**Comment by lakner** [comment]
This one?
```
class RemoteGame(models.Model) :
	player1 = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='player1')
	player2 = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='player2')
	created_at = models.DateTimeField(auto_now_add=True)
	started_at = models.DateTimeField(null=True)
	finished_at = models.DateTimeField(null=True)
	pointsP1 = models.IntegerField(default=0)
	pointsP2 = models.IntegerField(default=0)
	winner = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True, related_name='games_won')
	loser = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True, related_name='games_lost')
	finished = models.BooleanField(default=False)
```
I'm really looking to save per-user statistics for the leaderboard (games played, games won), hopefully without retrieving all the game data from the database.
